# Generated by Django 3.0.8 on 2020-07-28 07:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 7, 4, 44, 175294, tzinfo=utc)),
        ),
    ]
